### ISSUE TITLE
Upstream changing its handling of reading from stdin

### ISSUE THREAD

**Issue by brighid** [flowroute/ebb-lint#10]
Per https://github.com/flowroute/ebb-lint/pull/8#issuecomment-163788612 —we correctly handle the "you're being fed code from stdin" idiom in versions of flake8 earlier than 2.5.0, but in that version they're going to change the idiom, so we'll need to adapt to that.

**Comment by brighid** [comment]
The upstream change in question: https://gitlab.com/pycqa/flake8/commit/41393c9b6de513ea169b61c175b71018e8a12336 It looks like the new tactic they use is handing off a file object, which may actually be slightly easier to handle than creating one ourselves.

**Comment by habnabit** [comment]
I believe #11 fixed this.
