### ISSUE TITLE
flake8 sometimes runs at half speed or worse when ebb_lint is installed 

### ISSUE THREAD

**Issue by brighid** [flowroute/ebb-lint#12]
Here's what I got when I compared speeds over some of our codebase: 
```
| File         | Lines | flake8 (s) | normalized (μs) | ebb-lint (s) | normalized (μs) | slower by % |
|--------------+-------+------------+-----------------+--------------+-----------------+-------------|
| cdr.py       |   447 |       0.24 |             537 |         0.64 |            1432 |        167% |
| client.py    |   380 |       0.24 |             632 |         0.53 |            1395 |        121% |
| cnam.py      |   103 |       0.19 |            1845 |         0.36 |            3495 |         89% |
| consumers.py |   264 |       0.22 |             833 |         0.49 |            1856 |        123% |
| main.py      |    33 |       0.19 |            5758 |         0.31 |            9394 |         63% |
| mdr.py       |    76 |       0.19 |            2500 |         0.31 |            4079 |         63% |
| service.py   |   114 |       0.19 |            1667 |         0.38 |            3333 |        100% |
```
I'm going to try it on larger files next. This performance hit makes flycheck (emacs) run slowly enough that coding is harder.

**Comment by habnabit** [comment]
So, for what it's worth, my flycheck doesn't slow down emacs at all even if linting takes a while. I don't know if this is something I specifically turned on or what.

Either way, I did a minimal bit of profiling a few weeks ago and found that lib2to3 can be *really* slow in some cases. If lint speed is actually critical, I think it'll mean changing some of the tree matchers in the checkers to be faster, at the cost of being less representative of what's actually being matched.

**Comment by The-Compiler** [comment]
FWIW, for [my project](https://github.com/The-Compiler/qutebrowser), flake8 takes 18s without ebb-lint and 1m 8s with it (average of 3 runs).

**Comment by jordal** [comment]
This project is now maintained [elsewhere.](https://github.com/habnabit/ebb-lint) Since I'm unaware of any github feature to move an issue across repositories, please recreate your issue under the new maintainer.

**Comment by The-Compiler** [comment]
It looks like @habnabit hasn't turned on issues for his fork yet, though :wink:

**Comment by jordal** [comment]
I don't mind if this issue thread is used until then, or even until it's resolved. I had only intended to make it clear that the project has moved.

**Comment by habnabit** [comment]
<https://github.com/habnabit/ebb-lint/issues>! Didn't realize this was off by default.
